project:
  type: book

book:
  title: "Lag kommandolinje-verktøy i Python"
  description: "Workshop om å lage kommandolinje-verktøy med typer i Python"
  author:
    - name: Jørgen Nordmoen
      affiliation: NAV IT
      email: jorgen.halvorsen.nordmoen@nav.no
    - name: Sara Elise Wøllo
      affiliation: NAV IT
      email: Sara.Elise.Wollo@nav.no

  publisher: "NAV - Arbeids- og velferdsetaten"
  genre: "Workshop"

  license: "CC BY"
  language: "no"

  page-navigation: true
  repo-url: https://github.com/navikt/typer_cli_workshop
  twitter-card: true
  open-graph: true
  downloads: [epub]
  site-url: "https://data.ansatt.nav.no/story/c09048a0-3373-4cc6-af12-44d3beb6569b/"

  chapters:
    - index.qmd
    - setup.qmd
    - first_steps/first_steps.qmd
    - colors/colors.qmd
    - downloader/downloader.qmd

  navbar:
    logo: assets/nav_logo_hvit.png
    logo-alt: "Logo til NAV - Arbeids- og velferdsetaten"
    right:
      - icon: slack
        href: https://nav-it.slack.com/archives/C6WB7DXNC
        aria-label: Still spørsmål i \#data-science

format:
  html:
    date-modified: now
    date-format: "DD.MM.YYYY"
    lang: no
    theme:
      light: flatly
      dark: darkly
  epub:
    toc: true
