# Om workshopen {.unnumbered}

I denne workshopen skal vi sammen g친 gjennom hvordan man lager
kommandolinje-verkt칮y i Python med biblioteket
[`typer`](https://typer.tiangolo.com/).

Hvert kapittel i denne veiledningen er tiltenkt som et separat steg p친 veien mot
det endelige m친let. Vi anbefaler at du f칮lger kapittel for kapittel slik at man
ser sammenhengen, da hvert kapittel antar at man har fullf칮rt de foreg친ende.

Bruk menyen p친 venstreside, eller menyen nederst p친 hver side, for 친 navigere
gjennom kapitlene.

## Oppgaven
Vi tar sikte p친 친 bygge opp et enkelt kommandolinje-verkt칮y som tar inn p친
kommandolinjen nettsider og laster ned sidene. 

::: {.column-margin}
Vi forutsetter ingen kunnskap om hvordan man laster ned nettsider 游뗿
:::

- For 친 gj칮re oppgaven visuell 칮nsker vi 친 vise en fremdriftsindikator
  - Per nettside
  - Total fremdrift 
- Hvis bruker ber om det, p친 kommandolinjen, vis en oppsummering av hva som er
gjort.

![Animasjon av kommandolinje-verkt칮yet som laster ned VG, Aftenposten og NAV
sine forsider.](./assets/cli_workshop.gif)

## Elementer 친 legge merke til

For 친 oppfordre til deltakelse vil workshopen inneholder oppgaver som man
kan pr칮ve seg p친 selv, med tilh칮rende l칮sningsforslag. Det vil se omtrent slik
ut i teksten:

::: {.callout-tip}
## Oppgave
Smil til noen du er glad i!
:::

::: {.callout-note collapse="true"}
## L칮sningsforslag
游뱔
:::

For kode vil vi utheve med f칮lgende bokser:
```bash
python3 -c "print('Hello world!')" # <1>
```
1. Dette er en forklarende kommentar.

::: {.column-margin}
Legg merke til at alle kodeboksene har et lite ikon for utklippstavle 칮verst i
h칮yre hj칮rne, n친r du tar musepekeren over boksen.

Skulle du trenger 친 kopier alt som st친r i en boks 游땔.
:::

Dessverre s친 kan tallet som vises for kommentarer i kode havne over selve koden.
Dette gj칮r det vanskelig 친 lese koden under tallet. En l칮sning er 친 kopiere ut
teksten til en annen flate da tallene ikke blir med kopiering 游삔

